//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System;

[assembly: AssemblyCompany("Configit")]
[assembly: AssemblyVersion("3.0.1.1")]
[assembly: AssemblyFileVersion("3.0.1.1")]
[assembly: AssemblyInformationalVersion("3.0.1.1")]
[assembly: AssemblyCopyright("Copyright Configit A/S 2018")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]

